version: '3.8'

services:
  frontend:
    image: frontend-image
    ports:
      - "3000:3000"
    # env_file:
      - config.env  
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  backend:
    image: backend-image
    ports:
      - "4000:4000"
    # env_file:
      - config.env  
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
